# Docker Compose file for ROS2 MG400
services:
  ros2:
    container_name: ros2_humble_full
    image: ros2_humble_full:latest
    build:
      context: .
      dockerfile: Dockerfile  # Passe den Dateinamen ggf. an
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./ros2_ws:/root/ros2_ws
      - ./entrypoint.sh:/entrypoint.sh
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  ros2_ws:
